name: ci-golang-workflow

on:
  push:
  pull_request:

jobs:
  check-application:
    name: Go CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false

      - name: Run Go tests
        working-directory: ./go
        run: go test ./...

      - name: Run Go application
        working-directory: ./go
        run: go run math.go
